import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideNavbar from "@/components/SideNavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SpiritX_x-coders_02",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-900 flex">
        <SideNavbar />
        <main className="flex-1 ml-16 transition-all duration-300 ease-in-out">
          {" "}
          {children}
        </main>
      </body>
    </html>
  );
}
